// srm.client/src/components/DeTai/Edit.tsx
﻿import { useState, useEffect } from 'react';
import { Button, Form, Input, Row, Col, message, DatePicker, InputNumber, Select, Breadcrumb } from 'antd';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { CapDeTaiData, DeTaiData } from '../../models/data';
import { TacGiaJson } from '../../models/json';
import { createDeTai, editDeTai, getDetai } from '../../services/DeTaiService';
import { getCapDeTais } from '../../services/CapDeTaiService';
import { getDonViChuTris } from '../../services/DonViChuTriService';
import { getTacGiaDropDownData } from '../../services/TacGiaService';
import dayjs from 'dayjs';

const { TextArea } = Input;

export default () => {
    const [form] = Form.useForm();
    const [messageApi, contextHolder] = message.useMessage();
    const { id: idString } = useParams<{ id: string }>();
    const id = idString ? Number(idString) : undefined;
    const navigate = useNavigate();
    const [capDeTaiDatas, setCapDeTaiDatas] = useState<CapDeTaiData[]>([]);
    const [donViChuTriDatas, setDonViChuTriDatas] = useState<CapDeTaiData[]>([]);
    const [tacGiaJsons, setTacGiaJsons] = useState<TacGiaJson[]>([]);

    // Fetch danh sách tác giả
    const { data: tacGiaDropDownDatas } = useQuery({
        queryKey: ['tacGias'],
        queryFn: () => getTacGiaDropDownData(),
    });

    useEffect(() => {
        if (tacGiaDropDownDatas) {
            setTacGiaJsons(tacGiaDropDownDatas.map(item => ({
                id: item.id,
                ten: item.ten
            })));
        }
    }, [tacGiaDropDownDatas]);

    // Fetch dữ liệu đề tài
    const { data: deTaiData, isLoading: isDeTaiLoading, error: deTaiError } = useQuery({
        queryKey: ['deTai', id],
        queryFn: () => getDetai(id!),
        enabled: id !== undefined && !isNaN(id),
    });

    useEffect(() => {
        if (deTaiData) {
            let updatedTacGiaJsons = [...tacGiaJsons];
            const chuNhiem = deTaiData.chuNhiem;
            const canBoThamGias = deTaiData.canBoThamGias || [];

            // Xử lý chuNhiem
            if (chuNhiem) {
                const exists = tacGiaJsons.some(
                    (item) => item.id === chuNhiem.id && item.ten === chuNhiem.ten
                );
                if (!exists) {
                    updatedTacGiaJsons = [...updatedTacGiaJsons, chuNhiem];
                }
            }

            // Xử lý canBoThamGias
            canBoThamGias.forEach((canBo) => {
                const exists = updatedTacGiaJsons.some(
                    (item) => item.id === canBo.id && item.ten === canBo.ten
                );
                if (!exists) {
                    updatedTacGiaJsons = [...updatedTacGiaJsons, canBo];
                }
            });

            setTacGiaJsons(updatedTacGiaJsons);

            // Set giá trị form
            form.setFieldsValue({
                ...deTaiData,
                chuNhiem: chuNhiem ? JSON.stringify(chuNhiem) : null,
                canBoThamGias: canBoThamGias.map((item) => JSON.stringify(item)), // Chuyển thành danh sách chuỗi JSON
                ngayBatDau: deTaiData.ngayBatDau ? dayjs.utc(deTaiData.ngayBatDau).tz("Asia/Ho_Chi_Minh") : null,
                ngayKetThuc: deTaiData.ngayKetThuc ? dayjs.utc(deTaiData.ngayKetThuc).tz("Asia/Ho_Chi_Minh") : null,
            });
        }
    }, [deTaiData, form]);

    // Fetch danh sách cấp đề tài
    const { data: capDeTaiPage } = useQuery({
        queryKey: ['capDeTais'],
        queryFn: () => getCapDeTais({ pageIndex: 1, pageSize: 1000 }),
    });

    useEffect(() => {
        if (capDeTaiPage && capDeTaiPage.data) {
            setCapDeTaiDatas(capDeTaiPage.data);
        }
    }, [capDeTaiPage]);

    // Fetch danh sách cấp đề tài
    const { data: donViChuTriPage } = useQuery({
        queryKey: ['capDeTais'],
        queryFn: () => getDonViChuTris({ pageIndex: 1, pageSize: 1000 }),
    });

    useEffect(() => {
        if (donViChuTriPage && donViChuTriPage.data) {
            setDonViChuTriDatas(donViChuTriPage.data);
        }
    }, [donViChuTriPage]);

    // Xử lý submit form
    const onFinish = async (values: any) => {
        try {
            const formData: DeTaiData = {
                ten: values.ten,
                maSo: values.maSo,
                mucTieu: values.mucTieu,
                noiDung: values.noiDung,
                tongKinhPhi: values.tongKinhPhi,
                ngayBatDau: values.ngayBatDau ? values.ngayBatDau.toDate() : null,
                ngayKetThuc: values.ngayKetThuc ? values.ngayKetThuc.toDate() : null,
                kinhPhiHangNam: values.kinhPhiHangNam,
                hoSoNghiemThu: values.hoSoNghiemThu,
                hoSoSanPham: values.hoSoSanPham,
                donViChuTriId: typeof values.donViChuTriId === 'number' ? values.donViChuTriId : null,
                tenDonViChuTri: typeof values.donViChuTriId === 'string' ? values.donViChuTriId : null,
                capDeTaiId: typeof values.capDeTaiId === 'number' ? values.capDeTaiId : null,
                tenCapDeTai: typeof values.capDeTaiId === 'string' ? values.capDeTaiId : null,
                chuNhiem: values.chuNhiem != null ? JSON.parse(values.chuNhiem) : null,
                canBoThamGias: values.canBoThamGias ? values.canBoThamGias.map((item: string) => JSON.parse(item)) : [],
                phanChiaSuDongGop: values.phanChiaSuDongGop,
            };

            if (id !== undefined && !isNaN(id)) {
                await editDeTai(id, formData);
                messageApi.success('Cập nhật đề tài thành công!');
            } else {
                await createDeTai(formData);
                messageApi.success('Tạo đề tài thành công!');
            }
            navigate('/de-tai');
        } catch (error) {
            messageApi.error('Xảy ra lỗi khi xử lý!');
        }
    };

    return (
        <>
            {contextHolder}
            {(isDeTaiLoading) && <div>Đang tải dữ liệu...</div>}
            {(deTaiError) && <div>Lỗi khi tải dữ liệu</div>}
            <Breadcrumb
                style={{ marginTop: "10px" }}
                items={[{ title: "Đề tài" }, { title: id !== undefined && !isNaN(id) ? "Cập nhật" : "Ghi lại" }]}
            />
            <Form layout="vertical" form={form} onFinish={onFinish} style={{ marginTop: "10px" }} >
                <Row gutter={15}>                    
                    <Col span={12}>
                        <Form.Item name="ten" label="Tên đề tài" rules={[{ required: true, message: 'Vui lòng nhập tên đề tài!' }]}>
                            <Input placeholder="Nhập tên đề tài" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="maSo" label="Mã số" rules={[{ required: true, message: 'Vui lòng nhập mã số!' }]}>
                            <Input placeholder="Nhập mã số" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="mucTieu" label="Mục tiêu" rules={[{ required: true, message: 'Vui lòng nhập mục tiêu!' }]}>
                            <TextArea placeholder="Nhập mục tiêu" rows={3} />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="noiDung" label="Nội dung chính" rules={[{ required: true, message: 'Vui lòng nhập nội dung chính!' }]}>
                            <TextArea placeholder="Nhập nội dung" rows={3} />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="capDeTaiId" label="Cấp đề tài" rules={[{ required: true, message: 'Vui lòng chọn cấp đề tài!' }]}>
                            <Select
                                showSearch
                                placeholder="Chọn hoặc nhập cấp đề tài"
                                allowClear
                                filterOption={(input, option) =>
                                    option!.children?.toString().toLowerCase().includes(input.toLowerCase()) || input === ''
                                }
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter') {
                                        const target = e.target as HTMLInputElement
                                        const value = target.value;
                                        if (value && !capDeTaiDatas.some((item) => item.ten === value)) {
                                            setCapDeTaiDatas([...capDeTaiDatas, { id: null, ten: value }]);
                                            form.setFieldsValue({
                                                capDeTaiId: value,
                                            });
                                        }
                                    }
                                }}                                
                            >
                                {capDeTaiDatas.map((item, index) => (
                                    <Select.Option key={index} value={item.id} style={{ color: item.id ? 'blue' : 'black' }} >
                                        {item.ten}
                                    </Select.Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="tongKinhPhi" label="Tổng kinh phí" rules={[{ required: true, message: 'Vui lòng nhập tổng kinh phí!' }]}>
                            <InputNumber placeholder="Nhập tổng kinh phí" style={{ width: '100%' }} min={0} />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="kinhPhiHangNam" label="Kinh phí hàng năm">
                            <InputNumber placeholder="Nhập kinh phí hàng năm" style={{ width: '100%' }} min={0} />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="ngayBatDau" label="Thời gian bắt đầu" rules={[{ required: true, message: 'Vui lòng chọn ngày bắt đầu!' }]}>
                            <DatePicker style={{ width: '100%' }} format="DD/MM/YYYY" placeholder="Thời gian bắt đầu" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="ngayKetThuc" label="Thời gian kết thúc" rules={[{ required: true, message: 'Vui lòng chọn ngày kết thúc!' }]}>
                            <DatePicker style={{ width: '100%' }} format="DD/MM/YYYY" placeholder="Thời gian kết thúc" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="hoSoNghiemThu" label="Hồ sơ nghiệm thu">
                            <Input placeholder="Nhập thông tin hồ sơ nghiệm thu" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="hoSoSanPham" label="Hồ sơ sản phẩm">
                            <Input placeholder="Nhập thông tin hồ sơ sản phẩm" />
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item name="donViChuTriId" label="Đơn vị chủ tri" rules={[{ required: true, message: 'Vui lòng chọn đơn vị chủ trì!' }]}>
                            <Select
                                showSearch
                                placeholder="Chọn hoặc nhập đơn vị chủ trì"
                                allowClear
                                filterOption={(input, option) =>
                                    option!.children?.toString().toLowerCase().includes(input.toLowerCase()) || input === ''
                                }
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter') {
                                        const target = e.target as HTMLInputElement
                                        const value = target.value;
                                        if (value && !capDeTaiDatas.some((item) => item.ten === value)) {
                                            setDonViChuTriDatas([...capDeTaiDatas, { id: null, ten: value }]);
                                            form.setFieldsValue({
                                                donViChuTriId: value,
                                            });
                                        }
                                    }
                                }}
                            >
                                {donViChuTriDatas.map((item, index) => (
                                    <Select.Option key={index} value={item.id} style={{ color: item.id ? 'blue' : 'black' }} >
                                        {item.ten}
                                    </Select.Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item
                            name="chuNhiem"
                            label="Chủ nhiệm"
                            rules={[{ required: true, message: 'Vui lòng chọn chủ nhiệm!' }]}
                        >
                            <Select
                                showSearch
                                placeholder="Chọn chủ nhiệm"
                                allowClear
                                filterOption={(input, option) =>
                                    option?.children?.toString().toLowerCase().includes(input.toLowerCase()) || input === ''
                                }
                            >
                                {tacGiaJsons.map((item, index) => (
                                    <Select.Option
                                        key={index}
                                        value={JSON.stringify(item)}
                                        style={{ color: item.id ? 'blue' : 'black' }}
                                    >
                                        {item.ten}
                                    </Select.Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Col>
                    <Col span={12}>
                        <Form.Item
                            name="canBoThamGias"
                            label="Cán bộ tham gia"
                            rules={[{ required: true, message: 'Vui lòng chọn cán bộ tham gia!' }]}
                        >
                            <Select
                                mode="multiple"
                                showSearch
                                placeholder="Chọn cán bộ tham gia"
                                allowClear
                                filterOption={(input, option) =>
                                    option?.children?.toString().toLowerCase().includes(input.toLowerCase()) || input === ''
                                }
                            >
                                {tacGiaJsons.map((item, index) => (
                                    <Select.Option
                                        key={index}
                                        value={JSON.stringify(item)}
                                        style={{ color: item.id ? 'blue' : 'black' }}
                                    >
                                        {item.ten}
                                    </Select.Option>
                                ))}
                            </Select>
                        </Form.Item>
                    </Col>
                </Row>
                <Row justify="center">
                    <Form.Item>
                        <Button type="primary" htmlType="submit" loading={isDeTaiLoading}>
                            {id !== undefined && !isNaN(id) ? 'Cập nhật' : 'Ghi lại'}
                        </Button>
                        <Button style={{ marginLeft: '8px' }} onClick={() => navigate('/de-tai')}>
                            Quay lại
                        </Button>
                    </Form.Item>
                </Row>
            </Form>
        </>
    );
};

// srm.client/src/app/components/de-tai/edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { NzMessageService } from 'ng-zorro-antd/message';
import { DeTaiService } from '../../services/de-tai.service';
import { CapDeTaiService } from '../../services/cap-de-tai.service';
import { DonViChuTriService } from '../../services/don-vi-chu-tri.service';
import { TacGiaService } from '../../services/tac-gia.service';
import { DeTaiData, CapDeTaiData, TacGiaJson } from '../../models/data';
import * as dayjs from 'dayjs';
import * as utc from 'dayjs/plugin/utc';
import * as timezone from 'dayjs/plugin/timezone';

dayjs.extend(utc);
dayjs.extend(timezone);
dayjs.tz.setDefault("UTC");

@Component({
  selector: 'app-de-tai-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.css']
})
export class DeTaiEditComponent implements OnInit {
  deTaiForm: FormGroup;
  isEditMode: boolean = false;
  isDeTaiLoading: boolean = false;
  capDeTaiDatas: CapDeTaiData[] = [];
  donViChuTriDatas: CapDeTaiData[] = [];
  tacGiaJsons: TacGiaJson[] = [];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private message: NzMessageService,
    private deTaiService: DeTaiService,
    private capDeTaiService: CapDeTaiService,
    private donViChuTriService: DonViChuTriService,
    private tacGiaService: TacGiaService
  ) {
    this.deTaiForm = this.fb.group({
      ten: ['', [Validators.required]],
      maSo: ['', [Validators.required]],
      mucTieu: ['', [Validators.required]],
      noiDung: ['', [Validators.required]],
      capDeTaiId: [null, [Validators.required]],
      tongKinhPhi: [null, [Validators.required]],
      kinhPhiHangNam: [null],
      ngayBatDau: [null, [Validators.required]],
      ngayKetThuc: [null, [Validators.required]],
      hoSoNghiemThu: [''],
      hoSoSanPham: [''],
      donViChuTriId: [null, [Validators.required]],
      chuNhiem: [null, [Validators.required]],
      canBoThamGias: [null, [Validators.required]]
    });
  }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.isEditMode = true;
      this.loadDeTaiData(Number(id));
    }
    this.loadCapDeTaiDatas();
    this.loadDonViChuTriDatas();
    this.loadTacGiaJsons();
  }

  loadDeTaiData(id: number): void {
    this.isDeTaiLoading = true;
    this.deTaiService.getDeTai(id).subscribe({
      next: (data: DeTaiData) => {
        this.deTaiForm.patchValue({
          ...data,
          chuNhiem: data.chuNhiem ? JSON.stringify(data.chuNhiem) : null,
          canBoThamGias: data.canBoThamGias ? data.canBoThamGias.map(item => JSON.stringify(item)) : [],
          ngayBatDau: data.ngayBatDau ? dayjs.utc(data.ngayBatDau).tz("Asia/Ho_Chi_Minh") : null,
          ngayKetThuc: data.ngayKetThuc ? dayjs.utc(data.ngayKetThuc).tz("Asia/Ho_Chi_Minh") : null
        });
        this.isDeTaiLoading = false;
      },
      error: () => {
        this.message.error('Xảy ra lỗi khi tải dữ liệu đề tài!');
        this.isDeTaiLoading = false;
      }
    });
  }

  loadCapDeTaiDatas(): void {
    this.capDeTaiService.getCapDeTais({ pageIndex: 1, pageSize: 1000 }).subscribe({
      next: (data) => {
        this.capDeTaiDatas = data.data;
      },
      error: () => {
        this.message.error('Xảy ra lỗi khi tải dữ liệu cấp đề tài!');
      }
    });
  }

  loadDonViChuTriDatas(): void {
    this.donViChuTriService.getDonViChuTris({ pageIndex: 1, pageSize: 1000 }).subscribe({
      next: (data) => {
        this.donViChuTriDatas = data.data;
      },
      error: () => {
        this.message.error('Xảy ra lỗi khi tải dữ liệu đơn vị chủ trì!');
      }
    });
  }

  loadTacGiaJsons(): void {
    this.tacGiaService.getTacGiaDropDownData().subscribe({
      next: (data) => {
        this.tacGiaJsons = data.map(item => ({
          id: item.id,
          ten: item.ten
        }));
      },
      error: () => {
        this.message.error('Xảy ra lỗi khi tải dữ liệu tác giả!');
      }
    });
  }

  onSubmit(): void {
    if (this.deTaiForm.invalid) {
      for (const i in this.deTaiForm.controls) {
        if (this.deTaiForm.controls.hasOwnProperty(i)) {
          this.deTaiForm.controls[i].markAsDirty();
          this.deTaiForm.controls[i].updateValueAndValidity();
        }
      }
      return;
    }

    const formData: DeTaiData = {
      ...this.deTaiForm.value,
      chuNhiem: this.deTaiForm.value.chuNhiem ? JSON.parse(this.deTaiForm.value.chuNhiem) : null,
      canBoThamGias: this.deTaiForm.value.canBoThamGias ? this.deTaiForm.value.canBoThamGias.map((item: string) => JSON.parse(item)) : [],
      ngayBatDau: this.deTaiForm.value.ngayBatDau ? this.deTaiForm.value.ngayBatDau.toDate() : null,
      ngayKetThuc: this.deTaiForm.value.ngayKetThuc ? this.deTaiForm.value.ngayKetThuc.toDate() : null
    };

    if (this.isEditMode) {
      this.deTaiService.editDeTai(this.route.snapshot.paramMap.get('id')!, formData).subscribe({
        next: () => {
          this.message.success('Cập nhật đề tài thành công!');
          this.router.navigate(['/de-tai']);
        },
        error: () => {
          this.message.error('Xảy ra lỗi khi cập nhật đề tài!');
        }
      });
    } else {
      this.deTaiService.createDeTai(formData).subscribe({
        next: () => {
          this.message.success('Tạo đề tài thành công!');
          this.router.navigate(['/de-tai']);
        },
        error: () => {
          this.message.error('Xảy ra lỗi khi tạo đề tài!');
        }
      });
    }
  }

  onCancel(): void {
    this.router.navigate(['/de-tai']);
  }
}

<nz-breadcrumb>
  <nz-breadcrumb-item>
    <a routerLink="/de-tai">Đề tài</a>
  </nz-breadcrumb-item>
  <nz-breadcrumb-item>
    <span *ngIf="isEditMode">Cập nhật</span>
    <span *ngIf="!isEditMode">Ghi lại</span>
  </nz-breadcrumb-item>
</nz-breadcrumb>

<form nz-form [formGroup]="deTaiForm" (ngSubmit)="onSubmit()">
  <div nz-row [nzGutter]="15">
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="ten">Tên đề tài</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng nhập tên đề tài!'">
          <input nz-input formControlName="ten" id="ten" placeholder="Nhập tên đề tài" />
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="maSo">Mã số</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng nhập mã số!'">
          <input nz-input formControlName="maSo" id="maSo" placeholder="Nhập mã số" />
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="mucTieu">Mục tiêu</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng nhập mục tiêu!'">
          <textarea nz-input formControlName="mucTieu" id="mucTieu" placeholder="Nhập mục tiêu" rows="3"></textarea>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="noiDung">Nội dung chính</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng nhập nội dung chính!'">
          <textarea nz-input formControlName="noiDung" id="noiDung" placeholder="Nhập nội dung" rows="3"></textarea>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="capDeTaiId">Cấp đề tài</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn cấp đề tài!'">
          <nz-select formControlName="capDeTaiId" id="capDeTaiId" nzShowSearch nzAllowClear nzPlaceHolder="Chọn hoặc nhập cấp đề tài">
            <nz-option *ngFor="let item of capDeTaiDatas" [nzValue]="item.id" [nzLabel]="item.ten"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="tongKinhPhi">Tổng kinh phí</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng nhập tổng kinh phí!'">
          <nz-input-number formControlName="tongKinhPhi" id="tongKinhPhi" [nzMin]="0" nzPlaceHolder="Nhập tổng kinh phí"></nz-input-number>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label nzFor="kinhPhiHangNam">Kinh phí hàng năm</nz-form-label>
        <nz-form-control>
          <nz-input-number formControlName="kinhPhiHangNam" id="kinhPhiHangNam" [nzMin]="0" nzPlaceHolder="Nhập kinh phí hàng năm"></nz-input-number>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="ngayBatDau">Thời gian bắt đầu</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn ngày bắt đầu!'">
          <nz-date-picker formControlName="ngayBatDau" id="ngayBatDau" nzFormat="DD/MM/YYYY" nzPlaceHolder="Thời gian bắt đầu"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="ngayKetThuc">Thời gian kết thúc</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn ngày kết thúc!'">
          <nz-date-picker formControlName="ngayKetThuc" id="ngayKetThuc" nzFormat="DD/MM/YYYY" nzPlaceHolder="Thời gian kết thúc"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label nzFor="hoSoNghiemThu">Hồ sơ nghiệm thu</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="hoSoNghiemThu" id="hoSoNghiemThu" placeholder="Nhập thông tin hồ sơ nghiệm thu" />
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label nzFor="hoSoSanPham">Hồ sơ sản phẩm</nz-form-label>
        <nz-form-control>
          <input nz-input formControlName="hoSoSanPham" id="hoSoSanPham" placeholder="Nhập thông tin hồ sơ sản phẩm" />
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="donViChuTriId">Đơn vị chủ trì</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn đơn vị chủ trì!'">
          <nz-select formControlName="donViChuTriId" id="donViChuTriId" nzShowSearch nzAllowClear nzPlaceHolder="Chọn hoặc nhập đơn vị chủ trì">
            <nz-option *ngFor="let item of donViChuTriDatas" [nzValue]="item.id" [nzLabel]="item.ten"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="chuNhiem">Chủ nhiệm</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn chủ nhiệm!'">
          <nz-select formControlName="chuNhiem" id="chuNhiem" nzShowSearch nzAllowClear nzPlaceHolder="Chọn chủ nhiệm">
            <nz-option *ngFor="let item of tacGiaJsons" [nzValue]="item | json" [nzLabel]="item.ten"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </div>
    <div nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzRequired]="true" nzFor="canBoThamGias">Cán bộ tham gia</nz-form-label>
        <nz-form-control [nzErrorTip]="'Vui lòng chọn cán bộ tham gia!'">
          <nz-select formControlName="canBoThamGias" id="canBoThamGias" nzMode="multiple" nzShowSearch nzAllowClear nzPlaceHolder="Chọn cán bộ tham gia">
            <nz-option *ngFor="let item of tacGiaJsons" [nzValue]="item | json" [nzLabel]="item.ten"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </div>
  </div>
  <div nz-row nzJustify="center">
    <nz-form-item>
      <button nz-button nzType="primary" [nzLoading]="isDeTaiLoading" type="submit">
        {{ isEditMode ? 'Cập nhật' : 'Ghi lại' }}
      </button>
      <button nz-button nzType="default" (click)="onCancel()" style="margin-left: 8px;">
        Quay lại
      </button>
    </nz-form-item>
  </div>
</form>
