// srm.client/src/app/components/danh-muc/cap-de-tai.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { NzMessageService } from 'ng-zorro-antd/message';
import { CapDeTaiService } from '../../services/cap-de-tai.service';

@Component({
  selector: 'app-cap-de-tai',
  templateUrl: './cap-de-tai.component.html',
  styleUrls: ['./cap-de-tai.component.css']
})
export class CapDeTaiComponent implements OnInit {
  form: FormGroup;
  dataSource: any[] = [];
  isLoading = false;
  isEditing = false;
  editData: any = null;
  searchParams = {
    pageIndex: 1,
    pageSize: 10
  };
  totalItems = 0;

  constructor(
    private fb: FormBuilder,
    private message: NzMessageService,
    private capDeTaiService: CapDeTaiService
  ) {
    this.form = this.fb.group({
      ten: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    this.loadData();
  }

  loadData(): void {
    this.isLoading = true;
    this.capDeTaiService.getCapDeTais(this.searchParams).subscribe(
      (response: any) => {
        this.dataSource = response.data;
        this.totalItems = response.total;
        this.isLoading = false;
      },
      (error: any) => {
        this.message.error('Có lỗi xảy ra');
        this.isLoading = false;
      }
    );
  }

  handlePaginationChange(pageIndex: number, pageSize: number): void {
    this.searchParams.pageIndex = pageIndex;
    this.searchParams.pageSize = pageSize;
    this.loadData();
  }

  handleRowClick(data: any): void {
    this.editData = data;
    this.form.setValue({ ten: data.ten });
  }

  handleCreateNew(): void {
    this.form.reset();
    this.editData = null;
    this.isEditing = true;
  }

  handleEdit(): void {
    if (!this.editData) {
      this.message.warning('Vui lòng chọn một dòng để chỉnh sửa!');
      return;
    }
    this.isEditing = true;
  }

  handleCancelEdit(): void {
    if (this.editData) {
      this.form.setValue({ ten: this.editData.ten });
    } else {
      this.form.reset();
    }
    this.isEditing = false;
  }

  onSubmit(): void {
    if (this.form.invalid) {
      return;
    }

    const formData = this.form.value;

    if (this.editData) {
      this.capDeTaiService.editCapDeTai(this.editData.id, formData).subscribe(
        () => {
          this.message.success('Cập nhật thành công');
          this.loadData();
          this.isEditing = false;
        },
        (error: any) => {
          this.message.error('Có lỗi xảy ra');
        }
      );
    } else {
      this.capDeTaiService.createCapDeTai(formData).subscribe(
        () => {
          this.message.success('Tạo mới thành công');
          this.loadData();
          this.isEditing = false;
        },
        (error: any) => {
          this.message.error('Có lỗi xảy ra');
        }
      );
    }
  }
}

<div>
  <nz-breadcrumb>
    <nz-breadcrumb-item>
      <span>Danh mục</span>
    </nz-breadcrumb-item>
    <nz-breadcrumb-item>
      <span>Cấp đề tài</span>
    </nz-breadcrumb-item>
  </nz-breadcrumb>

  <div style="margin-top: 10px;">
    <nz-row [nzGutter]="15">
      <nz-col [nzSpan]="12">
        <nz-table #basicTable [nzData]="dataSource" [nzLoading]="isLoading" (nzCurrentPageDataChange)="onCurrentPageDataChange($event)">
          <thead>
            <tr>
              <th nzWidth="5%">STT</th>
              <th>Tên cấp đề tài</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let data of basicTable.data">
              <td>{{ data.stt + 1 }}</td>
              <td>{{ data.ten }}</td>
            </tr>
          </tbody>
        </nz-table>
        <app-pagination
          [current]="searchParams.pageIndex"
          [pageSize]="searchParams.pageSize"
          [total]="totalItems"
          (pageIndexChange)="handlePaginationChange($event)"
          (pageSizeChange)="handlePaginationChange(searchParams.pageIndex, $event)"
        ></app-pagination>
      </nz-col>
      <nz-col [nzSpan]="12">
        <nz-row [nzGutter]="10">
          <nz-col>
            <button nz-button nzType="primary" (click)="handleCreateNew()">Thêm mới</button>
          </nz-col>
          <nz-col>
            <button *ngIf="isEditing" nz-button nzType="primary" nzDanger (click)="handleCancelEdit()">Hủy</button>
            <button *ngIf="!isEditing" nz-button nzType="primary" (click)="handleEdit()">Chỉnh sửa</button>
          </nz-col>
        </nz-row>
        <form nz-form [formGroup]="form" (ngSubmit)="onSubmit()" style="margin-top: 10px;">
          <nz-form-item>
            <nz-form-label [nzRequired]="true" nzFor="ten">Tên đề tài</nz-form-label>
            <nz-form-control>
              <input nz-input formControlName="ten" placeholder="Nhập tên đề tài" [disabled]="!isEditing" />
            </nz-form-control>
          </nz-form-item>
          <nz-form-item>
            <nz-form-control>
              <button *ngIf="isEditing" nz-button nzType="primary" [disabled]="!form.valid">Ghi lại</button>
            </nz-form-control>
          </nz-form-item>
        </form>
      </nz-col>
    </nz-row>
  </div>
</div>

// srm.client/src/components/DanhMuc/CapDeTai.tsx
﻿import { Button, Form, Input, Row, Col, Breadcrumb, TableProps, Table, message, Popconfirm } from 'antd';
import { CapDeTaiData } from '../../models/data';
import { useState } from 'react';
import { CapDeTaiSearch } from '../../models/search';
import { useQuery } from '@tanstack/react-query';
import { getCapDeTais, editCapDeTai, createCapDeTai } from '../../services/CapDeTaiService';
import { Pagination } from '../commons';

interface DataType extends CapDeTaiData {
    key: string;
    stt: number;
}

const columns: TableProps<DataType>['columns'] = [
    {
        title: <div style={{ textAlign: 'center' }}>STT</div>,
        dataIndex: 'stt',
        key: 'stt',
        width: '5%',
        render: (_, record) => (
            <div style={{ textAlign: 'center' }}>{record.stt + 1}</div>
        ),
    },
    {
        title: <div style={{ textAlign: 'center' }}>Tên cấp đề tài</div>,
        key: 'ten',
        dataIndex: 'ten',
    },
];

const DanhMuc: React.FC = () => {
    const [form] = Form.useForm();
    const [messageApi, contextHolder] = message.useMessage();
    const [searchParams, setSearchParams] = useState<CapDeTaiSearch>({
        pageIndex: 1,
        pageSize: 10,
        ten: null,
    });
    const [editData, setEditData] = useState<CapDeTaiData | null>(null);
    const [isEditing, setIsEditing] = useState<boolean>(false);

    const { data: capDeTaiDatas, isLoading, error, refetch } = useQuery({
        queryKey: ['deTaiData', searchParams],
        queryFn: () => getCapDeTais(searchParams),
    });

    const dataSource: DataType[] = capDeTaiDatas?.data?.map((item, index) => ({
        ...item,
        key: item.id!.toString(),
        stt: (searchParams.pageIndex! - 1) * searchParams.pageSize! + index,
    })) || [];

    const totalItems = capDeTaiDatas?.total ?? dataSource.length;

    const handlePaginationChange = (pageIndex: number, pageSize: number) => {
        setSearchParams(prev => ({ ...prev, pageIndex, pageSize }));
    };

    const handleRowClick = (record: DataType) => {
        setEditData({ id: record.id, ten: record.ten });
        form.setFieldsValue({ ten: record.ten });
    };

    const handleCreateNew = () => {
        form.resetFields();
        setEditData(null);
        setIsEditing(true);
    }

    const handleEdit = () => {
        if (!editData) {
            messageApi.warning('Vui lòng chọn một dòng để chỉnh sửa!');
            return;
        }
        setIsEditing(true);
    };

    const handleCancelEdit = () => {
        if (editData) {
            form.setFieldsValue({ ten: editData.ten });
        } else {
            form.resetFields();
        }
        setIsEditing(false);
    };

    const onFinish = async (values: any) => {
        try {
            if (editData?.id) {
                await editCapDeTai(editData.id, { ...editData, ten: values.ten });                
                messageApi.success('Cập nhật thành công');
            } else {
                await createCapDeTai({ ten: values.ten });
                messageApi.success('Tạo mới thành công');
            }
            form.resetFields();
            setEditData(null);
            setIsEditing(false)
            refetch();
        } catch (err) {
            messageApi.error('Có lỗi xảy ra');
            console.error(err);
        }
    };

    if (error) return <div>{(error as Error).message}</div>;

    return (
        <>
            {contextHolder}
            <Breadcrumb style={{ marginTop: '10px' }} items={[{ title: 'Danh mục' }, { title: 'Cấp đề tài' }]} />            
            <Row gutter={15} style={{ marginTop: '10px' }}>
                <Col span={12}>
                    <Table<DataType>
                        columns={columns}
                        dataSource={dataSource}
                        pagination={false}
                        loading={isLoading}                        
                        rowClassName={() => 'cursor-pointer'}
                        onRow={(record) => ({
                            onClick: () => handleRowClick(record),
                        })}
                    />
                    <Pagination
                        current={searchParams.pageIndex!}
                        pageSize={searchParams.pageSize!}
                        total={totalItems}
                        onChange={handlePaginationChange}
                    />
                </Col>
                <Col span={12}>
                    <Row gutter={10}>
                        <Col>
                            <Button type="primary" onClick={handleCreateNew}>Thêm mới</Button>
                        </Col>
                        <Col>
                            {isEditing ? (
                                <Popconfirm
                                    title="Xác nhận"
                                    description="Dữ liệu sẽ không được lưu lại"
                                    onConfirm={handleCancelEdit}
                                    okText="Đồng ý"
                                    cancelText="Hủy"
                                    >
                                    <Button type="primary" danger>Hủy</Button>
                                </Popconfirm>                                
                            ) : (
                                <Button type="primary" variant="solid" color="green" onClick={handleEdit}>Chỉnh sửa</Button>
                            )}
                        </Col>
                    </Row>
                    <Form layout="vertical" form={form} onFinish={onFinish} style={{ marginTop: '10px' }} initialValues={{ ten: '' }}>
                        <Form.Item
                            name="ten"
                            label="Tên đề tài"
                            rules={[{ required: true, message: 'Vui lòng nhập tên đề tài!' }]}
                        >
                            <Input placeholder="Nhập tên đề tài" disabled={!isEditing} />
                        </Form.Item>
                        <Row justify="center">
                            <Form.Item>
                                {isEditing && (
                                    <Button type="primary" htmlType="submit">
                                        Ghi lại
                                    </Button>
                                )}
                            </Form.Item>
                        </Row>
                    </Form>
                </Col>
            </Row>
        </>
    );
};

export default DanhMuc;
