// srm.client/src/app/components/de-tai/home.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { DeTaiService } from '../../services/de-tai.service';
import { DeTaiData, DeTaiSearch } from '../../models/data';
import { NzMessageService } from 'ng-zorro-antd/message';

@Component({
  selector: 'app-de-tai-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class DeTaiHomeComponent implements OnInit {
  dataSource: DeTaiData[] = [];
  isLoading = false;
  searchParams: DeTaiSearch = {
    pageIndex: 1,
    pageSize: 10,
    ten: null,
  };
  totalItems = 0;

  constructor(
    private deTaiService: DeTaiService,
    private message: NzMessageService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.fetchData();
  }

  fetchData(): void {
    this.isLoading = true;
    this.deTaiService.getDeTais(this.searchParams).subscribe(
      (response) => {
        this.dataSource = response.data;
        this.totalItems = response.total;
        this.isLoading = false;
      },
      (error) => {
        this.message.error('Có lỗi xảy ra');
        this.isLoading = false;
      }
    );
  }

  handlePaginationChange(pageIndex: number, pageSize: number): void {
    this.searchParams.pageIndex = pageIndex;
    this.searchParams.pageSize = pageSize;
    this.fetchData();
  }
}

<div>
  <nz-breadcrumb>
    <nz-breadcrumb-item>
      <span>Đề tài</span>
    </nz-breadcrumb-item>
    <nz-breadcrumb-item>
      <span>Danh sách</span>
    </nz-breadcrumb-item>
  </nz-breadcrumb>

  <button nz-button nzType="primary" routerLink="/de-tai/tao-moi" style="margin-top: 10px;">
    Tạo mới
  </button>

  <nz-table #basicTable [nzData]="dataSource" [nzLoading]="isLoading" [nzPagination]="false" style="margin-top: 10px;">
    <thead>
      <tr>
        <th style="text-align: center;">STT</th>
        <th style="text-align: center;">Thông tin đề tài</th>
        <th style="text-align: center;">Thao tác</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let item of basicTable.data">
        <td style="text-align: center;">{{ item.stt + 1 }}</td>
        <td>
          <h2>{{ item.ten }} - {{ item.maSo }}</h2>
          <ul style="list-style-type: none;">
            <li><i class="fa fa-bookmark"></i> {{ item.mucTieu }}</li>
            <li><i class="fa fa-user"></i> {{ item.chuNhiem?.ten }}</li>
          </ul>
        </td>
        <td style="text-align: center;">
          <a [routerLink]="['/de-tai', item.id]">Chi tiết</a>
        </td>
      </tr>
    </tbody>
  </nz-table>

  <app-pagination
    [current]="searchParams.pageIndex"
    [pageSize]="searchParams.pageSize"
    [total]="totalItems"
    (pageIndexChange)="handlePaginationChange($event, searchParams.pageSize)"
    (pageSizeChange)="handlePaginationChange(searchParams.pageIndex, $event)"
  ></app-pagination>
</div>

// srm.client/src/components/CongBo/Home.tsx
﻿import React from 'react';
import { Breadcrumb, Button, Flex, Table } from 'antd';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import type { TableProps } from 'antd';
import type { CongBoData } from '../../models/data';
import type { CongBoSearch } from '../../models/search';
import { useQuery } from '@tanstack/react-query';

import { faUser, faBookmark } from "@fortawesome/free-solid-svg-icons";
import { Pagination } from '../commons';
import { Link } from 'react-router-dom';
import { getCongBos } from '../../services/CongBoService';

interface DataType extends CongBoData {
    key: string;
    stt: number
}

const columns: TableProps<DataType>['columns'] = [
    {
        title: <div style={{ textAlign: 'center' }}>STT</div>,
        dataIndex: 'stt',
        key: 'stt',
        width: '5%',
        render: (_, record) => (
            <div style={{ display: 'flex', justifyContent: 'center' }}>
                <div style={{ textAlign: 'center' }}>{record.stt + 1}</div>
            </div>
        )
    },
    {
        title: <div style={{ textAlign: 'center' }}>Thông tin công bố</div>,
        key: 'info',
        render: (_, record) => (
            <>
                //<h2>{`${record.ten} - ${record.maSo}`}</h2>
                //<ul style={{ listStyleType: 'none' }}>
                //    <li><FontAwesomeIcon icon={faBookmark} /> {record.mucTieu}</li>
                //    <li><FontAwesomeIcon icon={faUser} /> {record.chuNhiem?.ten}</li>
                //</ul>
            </>
        ),
    },
    {
        title: <div style={{ textAlign: 'center' }}>Thao tác</div>,
        key: 'action',
        width: '10%',
        render: (_, record) => (
            <div style={{ textAlign: 'center' }}>
                <Link to={`/cong-bo/${record.id}`}>Chi tiết</Link>
            </div>
        ),
    },
];

export default () => {
    const [searchParams, setSearchParams] = React.useState<CongBoSearch>({
        pageIndex: 1,
        pageSize: 10,
        ten: null,
    });

    const { data, isLoading, error } = useQuery({
        queryKey: ['deTaiData', searchParams],
        queryFn: () => getCongBos(searchParams)
    });

    const dataSource: DataType[] = data?.data
        ? data.data.map((item, index) => ({
            ...item,
            key: item.id!.toString(),
            stt: (searchParams.pageIndex! - 1) * searchParams.pageSize! + index,
        }))
        : [];

    const totalItems = data?.total ?? dataSource.length;

    const handlePaginationChange = (pageIndex: number, pageSize: number) => {
        setSearchParams({
            ...searchParams,
            pageIndex,
            pageSize,
        });
    };

    if (error) return <div>{(error as Error).message}</div>;

    return (
        <>
            <Breadcrumb
                style={{ marginTop: "10px" }}
                items={[{ title: "Công Bố" }, { title: "Danh sách" }]}
            />
            <Flex justify="flex-end">
                <Button
                    type="primary"
                    style={{ marginTop: "10px" }}
                >
                    <Link to={'/cong-bo/tao-moi'}>Tạo mới</Link>
                </Button>
            </Flex>
            <Table<DataType>
                columns={columns}
                dataSource={dataSource}
                pagination={false}
                loading={isLoading}
                style={{ marginTop: "10px" }}
            />
            <Pagination
                current={searchParams.pageIndex!}
                pageSize={searchParams.pageSize!}
                total={totalItems}
                onChange={handlePaginationChange}
            />
        </>
    );
}
